language: python

dist: bionic

python:
  - 3.6

script:
  - ./install.sh
  - ./uninstall.sh

jobs:
  include:
    - stage: documentation
      if: branch = master
      install: skip
      script: "curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin devops context-aware-prompt docs"
